name: Twitter Media Backup CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test to build docker image
        uses: docker/build-push-action@v5
        with:
          push: false
      - name: Bump version and push tag
        id: tagging
        if: contains(github.ref, 'master')
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: maxcleme/twitter-media-backup:${{ steps.tagging.outputs.new_tag }},maxcleme/twitter-media-backup:latest
